## numpy functions p2

In [4]:
import numpy as np 

arr=np.array([10,20,30,40,50,60])

np.min(arr) #give minimum value

10

In [5]:
np.max(arr) #give maximum value from array

60

In [15]:
np.argmin(arr) #argmin give index of minimum value 
#postion of minimum value


0

In [16]:
np.argmax(arr) #argmax give index of maximum value 
#postion of maximum value

5

In [17]:
np.sqrt(arr) #give square root of all values

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [18]:
np.sin(arr) #sin value

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

In [19]:
np.cos(arr) # give cos value

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

##### linspace fun

In [21]:
np.linspace(1,2,5)
#give value between with a same gap

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# functions

In [27]:
import numpy as np 

np.random.seed(110)
matrix=np.random.randint(1,25,9).reshape(3,3)
print(matrix)


[[ 1  4 16]
 [16  1 17]
 [17  7  3]]


In [28]:
np.sum(matrix) # sum of array

82

In [29]:
np.min(matrix)

1

In [32]:
np.min(matrix,axis=1)
#find the row wise min  "1"

array([1, 1, 3])

In [30]:
np.max(matrix)

17

In [33]:
np.max(matrix,axis=0)
#find colmn wise max "0"

array([17,  7, 17])

In [35]:
np.cumsum(matrix)
#give cumulative sum

array([ 1,  5, 21, 37, 38, 55, 72, 79, 82], dtype=int32)

In [36]:
np.cumsum(matrix,axis=0)

array([[ 1,  4, 16],
       [17,  5, 33],
       [34, 12, 36]], dtype=int32)